name: MyCAQM
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  file_picker: ^10.3.6
  firebase_storage: ^13.0.4
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  flutter_speed_dial: ^7.0.0
  lottie: ^3.1.2
  intl: ^0.20.2
  dio: ^5.2.1
  audioplayers: ^6.5.1
  just_audio: ^0.10.5
  just_audio_web: ^0.4.16
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4
  mockito: ^5.5.0
  firebase_auth_mocks: ^0.15.1
  fake_cloud_firestore: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/clinicA.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/Naruto_Jutsu_Notification.mp3
    - assets/sounds/MessageTone.mp3
    - assets/sounds/mixkit.wav