// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKoRf_ZcU9yIoEgtMytAABEUwT8ATuzjo',
    appId: '1:753203336186:web:f5259b99075b183907ca43',
    messagingSenderId: '753203336186',
    projectId: 'mycaqm',
    authDomain: 'mycaqm.firebaseapp.com',
    storageBucket: 'mycaqm.firebasestorage.app',
    measurementId: 'G-NLWZF8DMEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2y2B8oVofEc6JHHT2R3Z4J5YnoD93IMY',
    appId: '1:753203336186:android:65dff4f7f5cec72a07ca43',
    messagingSenderId: '753203336186',
    projectId: 'mycaqm',
    storageBucket: 'mycaqm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtw87SlHphJAcKc9J5VRfQZvjy2xKDjKY',
    appId: '1:753203336186:ios:b157165e9aa6449307ca43',
    messagingSenderId: '753203336186',
    projectId: 'mycaqm',
    storageBucket: 'mycaqm.firebasestorage.app',
    iosBundleId: 'com.example.caqm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtw87SlHphJAcKc9J5VRfQZvjy2xKDjKY',
    appId: '1:753203336186:ios:b157165e9aa6449307ca43',
    messagingSenderId: '753203336186',
    projectId: 'mycaqm',
    storageBucket: 'mycaqm.firebasestorage.app',
    iosBundleId: 'com.example.caqm1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKoRf_ZcU9yIoEgtMytAABEUwT8ATuzjo',
    appId: '1:753203336186:web:a03e8c7ff6eab7e507ca43',
    messagingSenderId: '753203336186',
    projectId: 'mycaqm',
    authDomain: 'mycaqm.firebaseapp.com',
    storageBucket: 'mycaqm.firebasestorage.app',
    measurementId: 'G-KNXEY5Y1XH',
  );
}
