// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFFRxQrt2luanVKQwl1IsRHLXaG34wQQ',
    appId: '1:995560112843:web:5c80bd1b1c07a7e0d9514e',
    messagingSenderId: '995560112843',
    projectId: 'mycaqm-f73f3',
    authDomain: 'mycaqm-f73f3.firebaseapp.com',
    storageBucket: 'mycaqm-f73f3.firebasestorage.app',
    measurementId: 'G-4QZTC0CC69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABb6TYHCUuGZopcO0kEkGsyW_xeFDB-vA',
    appId: '1:995560112843:android:6f52683a1b139b48d9514e',
    messagingSenderId: '995560112843',
    projectId: 'mycaqm-f73f3',
    storageBucket: 'mycaqm-f73f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeb3h41ftWAzNnpJdGW_DX-K4zgxXfh38',
    appId: '1:995560112843:ios:8befa865395f156dd9514e',
    messagingSenderId: '995560112843',
    projectId: 'mycaqm-f73f3',
    storageBucket: 'mycaqm-f73f3.firebasestorage.app',
    iosBundleId: 'com.example.st1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeb3h41ftWAzNnpJdGW_DX-K4zgxXfh38',
    appId: '1:995560112843:ios:8befa865395f156dd9514e',
    messagingSenderId: '995560112843',
    projectId: 'mycaqm-f73f3',
    storageBucket: 'mycaqm-f73f3.firebasestorage.app',
    iosBundleId: 'com.example.st1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFFRxQrt2luanVKQwl1IsRHLXaG34wQQ',
    appId: '1:995560112843:web:9e511b0d89bf1423d9514e',
    messagingSenderId: '995560112843',
    projectId: 'mycaqm-f73f3',
    authDomain: 'mycaqm-f73f3.firebaseapp.com',
    storageBucket: 'mycaqm-f73f3.firebasestorage.app',
    measurementId: 'G-H3M5L4HP98',
  );
}
