// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CZj7CcwHlMuh2O0xXHBFeFR61vxFsw0',
    appId: '1:515448414277:web:c8971e2a6a214cac37432c',
    messagingSenderId: '515448414277',
    projectId: 'caqm00',
    authDomain: 'caqm00.firebaseapp.com',
    storageBucket: 'caqm00.firebasestorage.app',
    measurementId: 'G-6H1LBTHGBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uLq083OAKyUiLPSnksi4WaP0gjEFhkw',
    appId: '1:515448414277:android:1569d2f295adab4e37432c',
    messagingSenderId: '515448414277',
    projectId: 'caqm00',
    storageBucket: 'caqm00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmegLFJWDy7EExdk3J3oF5oMT62ZJ00L4',
    appId: '1:515448414277:ios:b9c705f6d5bd14e337432c',
    messagingSenderId: '515448414277',
    projectId: 'caqm00',
    storageBucket: 'caqm00.firebasestorage.app',
    iosBundleId: 'com.example.try2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmegLFJWDy7EExdk3J3oF5oMT62ZJ00L4',
    appId: '1:515448414277:ios:b9c705f6d5bd14e337432c',
    messagingSenderId: '515448414277',
    projectId: 'caqm00',
    storageBucket: 'caqm00.firebasestorage.app',
    iosBundleId: 'com.example.try2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4CZj7CcwHlMuh2O0xXHBFeFR61vxFsw0',
    appId: '1:515448414277:web:4d9f32bea89dc17137432c',
    messagingSenderId: '515448414277',
    projectId: 'caqm00',
    authDomain: 'caqm00.firebaseapp.com',
    storageBucket: 'caqm00.firebasestorage.app',
    measurementId: 'G-NYG5C9QRKV',
  );
}
