// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy0Jz84AFfZEzf5Kb5GM0qIa-iSUJZvOw',
    appId: '1:86245425818:web:41a077af4cb550d6625523',
    messagingSenderId: '86245425818',
    projectId: 'caqm023',
    authDomain: 'caqm023.firebaseapp.com',
    storageBucket: 'caqm023.firebasestorage.app',
    measurementId: 'G-Q4WZZLLBVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZBW2v6oSubKkQqLPFtia793v6zb0VHGc',
    appId: '1:86245425818:android:94fc39eb5b2da727625523',
    messagingSenderId: '86245425818',
    projectId: 'caqm023',
    storageBucket: 'caqm023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6j9eR5X8JEDU8L9PGMY5KqLmqYgWgZUs',
    appId: '1:86245425818:ios:0ad61ed73c923f74625523',
    messagingSenderId: '86245425818',
    projectId: 'caqm023',
    storageBucket: 'caqm023.firebasestorage.app',
    iosBundleId: 'com.example.prototype1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6j9eR5X8JEDU8L9PGMY5KqLmqYgWgZUs',
    appId: '1:86245425818:ios:0ad61ed73c923f74625523',
    messagingSenderId: '86245425818',
    projectId: 'caqm023',
    storageBucket: 'caqm023.firebasestorage.app',
    iosBundleId: 'com.example.prototype1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy0Jz84AFfZEzf5Kb5GM0qIa-iSUJZvOw',
    appId: '1:86245425818:web:ef06f1b358688127625523',
    messagingSenderId: '86245425818',
    projectId: 'caqm023',
    authDomain: 'caqm023.firebaseapp.com',
    storageBucket: 'caqm023.firebasestorage.app',
    measurementId: 'G-E38VTWNR45',
  );
}
